Rails.application.routes.draw do
  get 'users/index'
  get "login" => "users#login_form"
  post "login" => "users#login"
  post "logout" => "users#logout"
  get "/signup" => "users#new"
  get "users/:id/edit" => "users#edit"
  post "users/:id/update" => "users#update"
  post "users/create" => "users#create"
  get "users/:id" => "users#show"
  get "posts/index" => "posts#index"
  get "posts/new" => "posts#new"
  get "posts/:id" => "posts#show"
  post "posts/create" => "posts#create"
  get "posts/:id/edit" => "posts#edit"
  post "posts/:id/destroy" => "posts#destroy"
  post "posts/:id/update" => "posts#update"
  get "/" => "home#top"
  get "about" => "home#about"
end
